import random
import os

# Lista de dicionários com palavras em português como chave e em inglês como valor
dicionarios = [
    {'cachorro': 'dog'},
    {'gato': 'cat'},
    {'banana': 'banana'},
    {'computador': 'computer'},
    {'elefante': 'elephant'},
    {'sol': 'sun'},
    {'lua': 'moon'},
    {'água': 'water'},
    {'fogo': 'fire'},
    {'terra': 'earth'},
    {'ar': 'air'},
    {'carro': 'car'},
    {'bicicleta': 'bicycle'},
    {'avião': 'airplane'},
    {'navio': 'ship'},
    {'trem': 'train'},
    {'ônibus': 'bus'},
    {'escola': 'school'},
    {'professor': 'teacher'},
    {'aluno': 'student'},
    {'escritório': 'office'},
    {'trabalho': 'work'},
    {'amor': 'love'},
    {'ódio': 'hate'},
    {'alegria': 'joy'},
    {'tristeza': 'sadness'},
    {'família': 'family'},
    {'amigo': 'friend'},
    {'inimigo': 'enemy'},
    {'coração': 'heart'},
    {'mente': 'mind'},
    {'corpo': 'body'},
    {'saúde': 'health'},
    {'doença': 'illness'},
    {'comida': 'food'},
    {'bebida': 'drink'},
    {'dinheiro': 'money'},
    {'tempo': 'time'},
    {'espaço': 'space'},
    {'filme': 'movie'},
    {'música': 'music'},
    {'arte': 'art'},
    {'cidade': 'city'},
    {'país': 'country'},
    {'mundo': 'world'},
    {'paz': 'peace'},
    {'guerra': 'war'},
    {'tecnologia': 'technology'},
    {'internet': 'internet'},
    {'software': 'software'},
    {'hardware': 'hardware'},
    {'programação': 'programming'},
    {'dados': 'data'},
    {'informação': 'information'},
    {'conhecimento': 'knowledge'},
    {'aprendizado': 'learning'},
    {'ensino': 'teaching'},
    {'viagem': 'travel'},
    {'aventura': 'adventure'},
    {'exploração': 'exploration'},
    {'natureza': 'nature'},
    {'animal': 'animal'},
    {'planta': 'plant'},
    {'humano': 'human'},
    {'vida': 'life'},
    {'morte': 'death'},
    {'passado': 'past'},
    {'presente': 'present'},
    {'futuro': 'future'},
    {'sonho': 'dream'},
    {'realidade': 'reality'},
    {'fantasia': 'fantasy'},
    {'história': 'history'},
    {'cultura': 'culture'},
    {'religião': 'religion'},
    {'ciência': 'science'},
    {'esporte': 'sport'},
    {'jogo': 'game'},
    {'riso': 'laughter'},
    {'choro': 'cry'},
    {'medo': 'fear'},
    {'coragem': 'courage'},
    {'sucesso': 'success'},
    {'fracasso': 'failure'},
     {'sorriso': 'smile'},
    {'lágrima': 'tear'},
    {'silêncio': 'silence'},
    {'barulho': 'noise'},
    {'sonho': 'dream'},
    {'pesadelo': 'nightmare'},
    {'esperança': 'hope'},
    {'desespero': 'despair'},
    {'liberdade': 'freedom'},
    {'prisão': 'prison'},
    {'ocasião': 'occasion'},
    {'celebração': 'celebration'},
    {'solidão': 'loneliness'},
    {'multidão': 'crowd'},
    {'passageiro': 'passenger'},
    {'motorista': 'driver'},
    {'destino': 'destination'},
    {'origem': 'origin'},
    {'conexão': 'connection'},
    {'isolamento': 'isolation'},
    {'cooperação': 'cooperation'},
    {'conflito': 'conflict'},
    {'companhia': 'company'},
    {'competição': 'competition'},
    {'cooperação': 'cooperation'},
    {'conflito': 'conflict'},
    {'companhia': 'company'},
    {'competição': 'competition'},
    {'cooperação': 'cooperation'},
    {'conflito': 'conflict'},
    {'companhia': 'company'},
    {'competição': 'competition'},
     {'celebridade': 'celebrity'},
    {'humildade': 'humility'},
    {'ambição': 'ambition'},
    {'conquista': 'achievement'},
    {'derrota': 'defeat'},
    {'vitória': 'victory'},
    {'reflexão': 'reflection'},
    {'contemplação': 'contemplation'},
    {'curiosidade': 'curiosity'},
    {'compreensão': 'understanding'},
    {'confiança': 'confidence'},
    {'dúvida': 'doubt'},
    {'sabedoria': 'wisdom'},
    {'ignorância': 'ignorance'},
    {'sinceridade': 'sincerity'},
    {'falsidade': 'dishonesty'},
    {'integridade': 'integrity'},
    {'corrupção': 'corruption'},
    {'respeito': 'respect'},
    {'desrespeito': 'disrespect'},
    {'tolerância': 'tolerance'},
    {'intolerância': 'intolerance'},
    {'paciência': 'patience'},
    {'impaciência': 'impatience'},
    {'compaixão': 'compassion'},
    {'indiferença': 'indifference'},
    {'gentileza': 'kindness'},
    {'crueldade': 'cruelty'},
    {'generosidade': 'generosity'},
    {'avareza': 'greed'},
    {'honestidade': 'honesty'},
    {'mentira': 'lie'},
    {'coragem': 'bravery'},
    {'covardia': 'cowardice'},
    {'alegria': 'happiness'},
    {'tristeza': 'sadness'},
    {'esperança': 'hope'},
    {'desespero': 'despair'},
    {'otimismo': 'optimism'},
    {'pessimismo': 'pessimism'},
    {'inovação': 'innovation'},
    {'tradição': 'tradition'},
    {'recompensa': 'reward'},
    {'punição': 'punishment'},
    {'surpresa': 'surprise'},
    {'previsibilidade': 'predictability'},
    {'desafio': 'challenge'},
    {'oportunidade': 'opportunity'},
    {'obstáculo': 'obstacle'},
    {'conquista': 'achievement'},
    {'fracasso': 'failure'},
    {'esperança': 'hope'},
    {'desespero': 'despair'},
        {'solidariedade': 'solidarity'},
    {'cooperação': 'cooperation'},
    {'compromisso': 'commitment'},
    {'responsabilidade': 'responsibility'},
    {'liberação': 'release'},
    {'aprisionamento': 'imprisonment'},
    {'inovação': 'innovation'},
    {'tradição': 'tradition'},
    {'recompensa': 'reward'},
    {'punição': 'punishment'},
    {'surpresa': 'surprise'},
    {'previsibilidade': 'predictability'},
    {'desafio': 'challenge'},
    {'oportunidade': 'opportunity'},
    {'obstáculo': 'obstacle'},
    {'conquista': 'achievement'},
    {'fracasso': 'failure'},
    {'mistério': 'mystery'},
    {'revelação': 'revelation'},
    {'nascimento': 'birth'},
    {'morte': 'death'},
    {'renascimento': 'rebirth'},
    {'corrupção': 'corruption'},
    {'pureza': 'purity'},
    {'cor': 'color'},
    {'preto': 'black'},
    {'branco': 'white'},
    {'vermelho': 'red'},
    {'azul': 'blue'},
    {'verde': 'green'},
    {'amarelo': 'yellow'},
    {'roxo': 'purple'},
    {'laranja': 'orange'},
    {'marrom': 'brown'},
    {'cinza': 'gray'},
    {'rosa': 'pink'},
    {'prata': 'silver'},
    {'ouro': 'gold'},
    {'plástico': 'plastic'},
    {'metal': 'metal'},
    {'madeira': 'wood'},
    {'tecido': 'fabric'},
    {'pedra': 'stone'},
    {'vidro': 'glass'},
    {'papel': 'paper'},
    {'eletricidade': 'electricity'},
    {'energia': 'energy'},
    {'calor': 'heat'},
    {'frio': 'cold'},
    {'vento': 'wind'},
    {'chuva': 'rain'},
    {'neve': 'snow'},
    {'tempestade': 'storm'},
    {'céu': 'sky'},
    {'terra': 'earth'},
    {'lua': 'moon'},
    {'sol': 'sun'},
    {'estrela': 'star'},
    {'universo': 'universe'},
    # Adicione mais palavras conforme necessário
]

def limpar_tela():
    # Função para limpar a tela do console
    os.system('cls' if os.name == 'nt' else 'clear')

def jogo():
    palavras_passadas = set()  # Conjunto para armazenar palavras já perguntadas

    while True:
        # Limpa a tela a cada iteração
        limpar_tela()

        # Escolhe aleatoriamente um dicionário da lista, garantindo que não seja uma palavra já perguntada
        dicionario_atual = random.choice([d for d in dicionarios if list(d.keys())[0] not in palavras_passadas])
        palavra_portugues = list(dicionario_atual.keys())[0]
        palavra_ingles = list(dicionario_atual.values())[0]

        while True:
            # Solicita ao usuário a tradução da palavra em português
            resposta_usuario = input(f"Traduza a palavra '{palavra_portugues}' para inglês: ").lower()

            # Verifica se a resposta do usuário está correta
            if resposta_usuario == palavra_ingles.lower():
                print("Você acertou!\n")
                break
            else:
                print(f"Ops, resposta incorreta. Tente novamente.\n")

        # Adiciona a palavra em português ao conjunto de palavras já perguntadas
        palavras_passadas.add(palavra_portugues)

        # Verifica se todas as palavras já foram perguntadas
        if len(palavras_passadas) == len(dicionarios):
            print("Você acertou todas as palavras! Parabéns!")
            break

if __name__ == "__main__":
    jogo()
